@echo off
echo Creating fresh virtual environment...
python -m venv .venv
echo Activating virtual environment...
call .venv\Scripts\activate.bat
echo Installing dependencies...
pip install fastapi "uvicorn[standard]" sqlalchemy aiosqlite psycopg2-binary pydantic pydantic-settings httpx redis "passlib[bcrypt]" "python-jose[cryptography]" opentelemetry-api opentelemetry-sdk opentelemetry-instrumentation-fastapi opentelemetry-instrumentation-httpx opentelemetry-instrumentation-sqlalchemy opentelemetry-exporter-otlp python-json-logger
echo Starting server...
set PYTHONPATH=%cd%
uvicorn backend.app.main:app --host 0.0.0.0 --port 8000
pause
