import httpx
import logging
from typing import Dict, Any

from backend.app.core.config import get_settings

logger = logging.getLogger(__name__)


class HuggingFaceClient:
    def __init__(self):
        settings = get_settings()
        self.settings = settings
        self.api_key = getattr(settings, "HUGGINGFACE_API_KEY", None)
        if self.api_key:
            self.api_key = self.api_key.strip()
        if not self.api_key:
            logger.warning(
                "HUGGINGFACE_API_KEY is not configured in settings. "
                "Falling back to mock responses."
            )

        # Hugging Face has migrated the legacy Inference API to the Router endpoint.
        # This is an OpenAI-compatible API surface.
        self.base_url = "https://router.huggingface.co/v1"

    async def generate_text(self, model_id: str, prompt: str, max_tokens: int = 1024, temperature: float = 0.7) -> Dict[str, Any]:
        """
        Calls Hugging Face Router (OpenAI-compatible chat completions).
        """
        url = f"{self.base_url}/chat/completions"
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
        
        payload = {
            "model": model_id,
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": max_tokens,
            "temperature": temperature,
            "stream": False,
        }
        
        async with httpx.AsyncClient() as client:
            try:
                if not self.api_key:
                    # Mock Response Logic for learning/replication projects
                    import asyncio
                    import random
                    await asyncio.sleep(0.8 + random.random() * 1.5) # Simulate network + inference latency
                    
                    if "code" in prompt.lower() or "python" in prompt.lower():
                        mock_text = f"// [Mock Response from {model_id}]\n\ndef mock_solution():\n    # This is a simulated response for prompt: \"{prompt[:30]}...\"\n    return \"In a real deployment, this would be generated by a fine-tuned coding model.\""
                    else:
                        mock_text = f"[Inference Simulated: {model_id}]\n\nYou asked: \"{prompt[:50]}...\"\n\nResponse: This is a placeholder response. In a production environment with a valid HUGGINGFACE_API_KEY, the gateway would route this request to the {model_id} endpoint and return a real-time completion. This replication demonstrates the full end-to-end request/response cycle."

                    return {"text": mock_text, "status": "success"}

                response = await client.post(url, headers=headers, json=payload, timeout=30.0)
                response.raise_for_status()
                result = response.json()

                # OpenAI-compatible chat completion format
                content = (
                    result.get("choices", [{}])[0]
                    .get("message", {})
                    .get("content", "")
                )
                return {"text": content, "status": "success"}
                    
            except httpx.HTTPStatusError as exc:
                status_code = exc.response.status_code
                body = exc.response.text
                logger.error("HF API HTTP error: %s - %s", status_code, body)

                # Return detailed error so callers can surface meaningful info in UI.
                # In non-debug mode, we still keep the payload terse.
                payload: Dict[str, Any] = {
                    "status": "error",
                    "error": f"HF API Error: {status_code}",
                    "status_code": status_code,
                }
                if getattr(self.settings, "DEBUG", False):
                    payload["details"] = body[:2000]
                return payload
            except Exception as exc:
                logger.error("HF API connection error: %s", exc)
                payload: Dict[str, Any] = {"status": "error", "error": f"HF Connection Error: {exc}"}
                return payload
